import mysql.connector as a 
con=a.connect(host='localhost',user='root',passwd='veerkhushal',database='cardealership')
print("\t\t............................................................")
print("\t\t\t\t*****WELCOME TO CAR DEALERSHIP MANAGEMENT SYSTEM*****")
print("\t\t............................................................")
print("\n\t\t\t\t\t****** VEER *******")
def login():
      a=input("Enter a Name :")
      b=int(input("Enter id"))
      c=con.cursor()
      c.execute(a,b)
      con.commit()
      print("Login Successfully")
      print(a)
      print(b)
def buy():
      c=input("Enter Car Name :")
      d=input("Eenter Car Color :")
      e=input("Enter Car price :")
      z=con.cursor()
      z.execute(c,d,e)
      print(c)
      print(d)
      print(e)
def sale():
      a=input("Enter Car Owner Name :")
      z=input("Enter Car Name :")
      b=int(input("Enter Car Sale Price :"))
      c=input("Enter Car Color :")
      d=input("Enter Buyer Name :")
      f=con.execute()
      f.execute(a,z,b,c,d)
      print(a)
      print(b)
      print(c)
      print(d)
      print(z)